[package]
name = "pw_tokenizer_core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core tokenizer functionality for pw_tokenizer"

[lib]
path = "../pw_tokenizer_core.rs"

[features]
default = []
std = []
